export const Bottomlist = [
  {
    id: 1,
    page: '',
    icon: 'home-outline',
    iconfocus: 'home',
    text: 'Home',
    header: true,
  },
  {
    id: 2,
    page: '',
    icon: 'pizza-outline',
    iconfocus: 'pizza',
    text: 'Recipe',
    header: false,
  },
  {
    id: 3,
    page: '',
    icon: 'search-outline',
    iconfocus: 'search-sharp',
    text: 'Search',
    header: true,
  },
  {
    id: 4,
    page: '',
    icon: 'heart-outline',
    iconfocus: 'heart-sharp',
    text: 'Favorite',
    header: true,
  },
  {
    id: 5,
    page: '',
    icon: 'person-outline',
    iconfocus: 'person-sharp',
    text: 'Profile',
    header: true,
  },
];
